// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/products" | "/products/[slug]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = "/booth.html" | "/en" | "/index.html" | "/ja/[[...path]]" | "/ja/booth.html" | "/ja/index.html" | "/ja/product-bj-motion.html" | "/ja/product-dark-voice-material.html" | "/ja/product-dosukebe-material.html" | "/ja/product-foot-motion.html" | "/ja/product-hand-motion.html" | "/ja/product-sexy-attack-motion-vol1.html" | "/ja/product-sexy-motion-attack-vol2.html" | "/ja/product-sexy-motion-vol1.html" | "/ja/product-sexy-pose-eku.html" | "/ja/product-sexy-pose-ichigo.html" | "/ja/product-sexy-pose-kumaly.html" | "/ja/product-sexy-pose-lumina.html" | "/ja/product-sexy-pose-milltina.html" | "/ja/product-sexy-pose-plum-chocolat.html" | "/ja/product-sexy-pose-ramune.html" | "/ja/product-sexy-pose-rurune.html" | "/ja/product-sexy-pose-shinano.html" | "/ja/product-solo-motion-vol1.html" | "/ja/product-solo-motion-vol2.html" | "/ja/product-solo-motion-vol3.html" | "/ja/product-solo-motion-vol4.html" | "/product-bj-motion.html" | "/product-dark-voice-material.html" | "/product-dosukebe-material.html" | "/product-foot-motion.html" | "/product-hand-motion.html" | "/product-sexy-attack-motion-vol1.html" | "/product-sexy-motion-attack-vol2.html" | "/product-sexy-motion-vol1.html" | "/product-sexy-pose-eku.html" | "/product-sexy-pose-ichigo.html" | "/product-sexy-pose-kumaly.html" | "/product-sexy-pose-lumina.html" | "/product-sexy-pose-milltina.html" | "/product-sexy-pose-plum-chocolat.html" | "/product-sexy-pose-ramune.html" | "/product-sexy-pose-rurune.html" | "/product-sexy-pose-shinano.html" | "/product-solo-motion-vol1.html" | "/product-solo-motion-vol2.html" | "/product-solo-motion-vol3.html" | "/product-solo-motion-vol4.html" | "/products/dark-voice-material"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/booth.html": {}
  "/en": {}
  "/index.html": {}
  "/ja/[[...path]]": { "path"?: string[]; }
  "/ja/booth.html": {}
  "/ja/index.html": {}
  "/ja/product-bj-motion.html": {}
  "/ja/product-dark-voice-material.html": {}
  "/ja/product-dosukebe-material.html": {}
  "/ja/product-foot-motion.html": {}
  "/ja/product-hand-motion.html": {}
  "/ja/product-sexy-attack-motion-vol1.html": {}
  "/ja/product-sexy-motion-attack-vol2.html": {}
  "/ja/product-sexy-motion-vol1.html": {}
  "/ja/product-sexy-pose-eku.html": {}
  "/ja/product-sexy-pose-ichigo.html": {}
  "/ja/product-sexy-pose-kumaly.html": {}
  "/ja/product-sexy-pose-lumina.html": {}
  "/ja/product-sexy-pose-milltina.html": {}
  "/ja/product-sexy-pose-plum-chocolat.html": {}
  "/ja/product-sexy-pose-ramune.html": {}
  "/ja/product-sexy-pose-rurune.html": {}
  "/ja/product-sexy-pose-shinano.html": {}
  "/ja/product-solo-motion-vol1.html": {}
  "/ja/product-solo-motion-vol2.html": {}
  "/ja/product-solo-motion-vol3.html": {}
  "/ja/product-solo-motion-vol4.html": {}
  "/product-bj-motion.html": {}
  "/product-dark-voice-material.html": {}
  "/product-dosukebe-material.html": {}
  "/product-foot-motion.html": {}
  "/product-hand-motion.html": {}
  "/product-sexy-attack-motion-vol1.html": {}
  "/product-sexy-motion-attack-vol2.html": {}
  "/product-sexy-motion-vol1.html": {}
  "/product-sexy-pose-eku.html": {}
  "/product-sexy-pose-ichigo.html": {}
  "/product-sexy-pose-kumaly.html": {}
  "/product-sexy-pose-lumina.html": {}
  "/product-sexy-pose-milltina.html": {}
  "/product-sexy-pose-plum-chocolat.html": {}
  "/product-sexy-pose-ramune.html": {}
  "/product-sexy-pose-rurune.html": {}
  "/product-sexy-pose-shinano.html": {}
  "/product-solo-motion-vol1.html": {}
  "/product-solo-motion-vol2.html": {}
  "/product-solo-motion-vol3.html": {}
  "/product-solo-motion-vol4.html": {}
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/products/dark-voice-material": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
